menu:
- {name: 'about me', url: '/index'}
- {name: 'courses', url: '/courses'}
- {name: 'curriculum vitae', url: '/cv'}
- {name: 'publications', url: '/publications'}

social:
- {icon: 'github', link: 'https://github.com/AraujoMat'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Matheus-De-Araujo-4?ev=hdr_xprf'}
