menu:
- {name: 'About me', url: '/index'}
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}

social:
- {icon: 'github', link: 'https://github.com/AraujoMat'}
