menu:
- {name: 'about', url: '/index'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'publications', url: '/publications'}

social:
- {icon: 'google-scholar', link: 'https://scholar.google.com.br/citations?user=lx_buUAAAAAJ&hl=pt-BR&oi=ao'}
- {icon: 'github', link: 'https://github.com/AraujoMat'}
- {icon: 'lattes', link: 'http://lattes.cnpq.br/6656236239929064'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Matheus-De-Araujo-4?ev=hdr_xprf'}
